version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  # Backend 
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile
    container_name: nestjs_backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: inventory_db
    networks:
      - app_network

  # Frontend 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3001:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000 
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
